
```{r appendix, include=FALSE}
```
# Appendices {.tabset}
## *Appendix 1.Decomposition Comparison*

* Classical Decomposition assumes seasonal component repeats from year to year, which usually is not the case in reality, over smoothes rapid rises (is not recommended to use, but still...).
* STL Decomposition is a versatile and robust method that handles any seasonality; seasonal components can change, and smoothness can be controlled.
* X-11 method originated in the US Census Bureau and was further developed by Statistics Canada, based on classical decomposition, a slightly improved version of classical decomposition; the seasonal component varies slowly over time, highly robust to outliers and level shifts in the time series.


## *Appendix 2. Accuracy metrics comparison*
*AIC* criteria are used to assess the goodness of fit of a model, with lower values indicating a better fit.
*RMSE* and MAE are used to measure the difference between predicted values and actual values. Comparatively lower numbers of these metrics assume a better model's forecast quality potential. 
