# Decomposition

As time series data often consists of different patterns, it is helpful to split time series into components, each representing a pattern category. As a result, we can understand how each element behaves over time and model each separately for greater forecasting accuracy results. It will also help to decide on the type of forecasting model.

For this purpose, we considered different types of decomposition techniques:
* Classical Decomposition assumes seasonal component repeats from year to year, which usually is not the case in reality, over smoothes rapid rises (is not recommended to use, but still...).
* STL Decomposition is a versatile and robust method that handles any seasonality; seasonal components can change, and smoothness can be controlled.
* X-11 method originated in the US Census Bureau and was further developed by Statistics Canada, based on classical decomposition, a slightly improved version of classical decomposition; the seasonal component varies slowly over time, highly robust to outliers and level shifts in the time series.
We decided to continue with STL Decomposition.

## Decomposition for all countries

```{r}

#STL Decomposition_Germany
data_elec %>%
  model(STL(Germany ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

#STL Decomposition_France
data_elec %>%
  model(STL(France ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

#STL Decomposition_Italy
data_elec %>%
  model(STL(Italy ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

#STL Decomposition_Austria
data_elec %>%
  model(STL(Austria ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

#STL Decomposition_Lichtenstein
data_elec %>%
  model(STL(Lichtenstein ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()

#STL Decomposition_Total
data_elec %>%
  model(STL(Total ~ trend(window = 7) + season(window = "periodic"),
    robust = TRUE)) %>%
  components() %>%
  autoplot()


```

We observe strong seasonality and trend patterns in each country and all countries together. The data is non-stationary. 




