<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />

    
        <meta name="date" content="2023-05-08" />
    
    <title>Forecasting Project 1 - Group 7</title>

        <script src="main_files/header-attrs-2.21/header-attrs.js"></script>
        <script src="main_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="main_files/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <script src="main_files/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <script src="main_files/navigation-1.1/tabsets.js"></script>
        <script src="main_files/navigation-1.1/codefolding.js"></script>
        <link href="main_files/readthedown-0.1/readthedown.css" rel="stylesheet" />
        <link href="main_files/readthedown-0.1/readthedown_fonts_embed.css" rel="stylesheet" />
        <script src="main_files/readthedown-0.1/readthedown.js"></script>
    
    
        <style type="text/css">code{white-space: pre;}</style>
    <style type="text/css">
      pre > code.sourceCode { white-space: pre; position: relative; }
      pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
      pre > code.sourceCode > span:empty { height: 1.2em; }
      .sourceCode { overflow: visible; }
      code.sourceCode > span { color: inherit; text-decoration: inherit; }
      div.sourceCode { margin: 1em 0; }
      pre.sourceCode { margin: 0; }
      @media screen {
      div.sourceCode { overflow: auto; }
      }
      @media print {
      pre > code.sourceCode { white-space: pre-wrap; }
      pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
      }
      pre.numberSource code
        { counter-reset: source-line 0; }
      pre.numberSource code > span
        { position: relative; left: -4em; counter-increment: source-line; }
      pre.numberSource code > span > a:first-child::before
        { content: counter(source-line);
          position: relative; left: -1em; text-align: right; vertical-align: baseline;
          border: none; display: inline-block;
          -webkit-touch-callout: none; -webkit-user-select: none;
          -khtml-user-select: none; -moz-user-select: none;
          -ms-user-select: none; user-select: none;
          padding: 0 4px; width: 4em;
          background-color: #2a211c;
          color: #bdae9d;
        }
      pre.numberSource { margin-left: 3em; border-left: 1px solid #bdae9d;  padding-left: 4px; }
      div.sourceCode
        { color: #bdae9d; background-color: #2a211c; }
      @media screen {
      pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
      }
      code span.al { color: #ffff00; } /* Alert */
      code span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
      code span.at { } /* Attribute */
      code span.bn { color: #44aa43; } /* BaseN */
      code span.bu { } /* BuiltIn */
      code span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
      code span.ch { color: #049b0a; } /* Char */
      code span.cn { } /* Constant */
      code span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
      code span.do { color: #0066ff; font-style: italic; } /* Documentation */
      code span.dt { text-decoration: underline; } /* DataType */
      code span.dv { color: #44aa43; } /* DecVal */
      code span.er { color: #ffff00; font-weight: bold; } /* Error */
      code span.ex { } /* Extension */
      code span.fl { color: #44aa43; } /* Float */
      code span.fu { color: #ff9358; font-weight: bold; } /* Function */
      code span.im { } /* Import */
      code span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
      code span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
      code span.op { } /* Operator */
      code span.pp { font-weight: bold; } /* Preprocessor */
      code span.sc { color: #049b0a; } /* SpecialChar */
      code span.ss { color: #049b0a; } /* SpecialString */
      code span.st { color: #049b0a; } /* String */
      code span.va { } /* Variable */
      code span.vs { color: #049b0a; } /* VerbatimString */
      code span.wa { color: #ffff00; font-weight: bold; } /* Warning */
    </style>
    
    
    <!-- tabsets -->
    <script>
      $(document).ready(function () {
	  window.buildTabsets("toc");
      });
      $(document).ready(function () {
	  $('.tabset-dropdown > .nav-tabs > li').click(function () {
	      $(this).parent().toggleClass('nav-tabs-open')
	  });
      });
    </script>

    <!-- code folding -->
        <script>
      $(document).ready(function () {
	  	  	  window.initializeCodeFolding("hide" === "show");
	        });
    </script>
    
    <!-- code download -->
    
    <!-- tabsets dropdown -->

    <style type="text/css">
      .tabset-dropdown > .nav-tabs {
	  display: inline-table;
	  max-height: 500px;
	  min-height: 44px;
	  overflow-y: auto;
	  background: white;
	  border: 1px solid #ddd;
	  border-radius: 4px;
      }
      
      .tabset-dropdown > .nav-tabs > li.active:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
	  content: "&#xe258;";
	  border: none;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs > li.active {
	  display: block;
      }

      .tabset-dropdown > .nav-tabs > li.active a {
  	  padding: 0 15px !important;
      }

      .tabset-dropdown > .nav-tabs > li > a,
      .tabset-dropdown > .nav-tabs > li > a:focus,
      .tabset-dropdown > .nav-tabs > li > a:hover {
	  border: none;
	  display: inline-block;
	  border-radius: 4px;
	  background-color: transparent;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li {
	  display: block;
	  float: none;
      }
      
      .tabset-dropdown > .nav-tabs > li {
	  display: none;
	  margin-left: 0 !important;
      }
    </style>
    
</head>

<body class="preload">

   	
         <!-- readthedown start -->   
   <div id="content" data-toggle="wy-nav-shift">
     <nav id="nav-top" role="navigation" aria-label="top navigation">
       <a role="button" href="#" data-toggle="wy-nav-top"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
     </nav>
         
      <div class="btn-group pull-right">
     <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
     <ul class="dropdown-menu" style="min-width: 50px;">
	    	    <li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
	    <li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
	    	    	         </ul>
   </div>
   
        
      <h1 class="title">Forecasting Project 1 - Group 7</h1>
      
         <!-- readthedown authors -->
   <div id="sidebar">
    <h2><a href="#content">Forecasting Project 1 - Group 7</a></h2>
    <div id="toc">
      <ul>
      <li><a href="#data-cleaning" id="toc-data-cleaning">Data
      cleaning</a></li>
      <li><a href="#exploratory-data-analysis"
      id="toc-exploratory-data-analysis">Exploratory Data
      Analysis</a></li>
      <li><a href="#autocorrelation"
      id="toc-autocorrelation">Autocorrelation</a></li>
      <li><a href="#models" id="toc-models">Models</a></li>
      <li><a href="#italy" id="toc-italy">Italy</a></li>
      <li><a href="#austria" id="toc-austria">Austria</a></li>
      <li><a href="#france" id="toc-france">France</a></li>
      <li><a href="#germany" id="toc-germany">Germany</a></li>
      </ul>
    </div>
    <div id="postamble" data-toggle="wy-nav-shift" class="status">
                  <p class="author"><span class="glyphicon glyphicon-user"></span> K
K A I
		      </p>
                        <p class="date"><span class="glyphicon glyphicon-calendar"></span> 2023-05-08</p>
          </div>
   </div>
     

   
      
   
<!-- Don't indent these lines or it will mess pre blocks indentation --> 
<div id="main">
<div id="data-cleaning" class="section level2">
<h2>Data cleaning</h2>
<p>We import data and we clean it from <i>NA</i> and from blank rows. We
also name the columns. Here is a sample of our data:</p>
<pre><code>##            date germany france italy austria lichtenstein total
## 1  January 2000     421    313  1760       3           24  2521
## 2 February 2000     412    141  1757       4           23  2337
## 3    March 2000     459    148  1962       4           23  2596
## 4    April 2000     474    114  1767       3           17  2375
## 5      May 2000     935    116  1927      42           14  3034
## 6     June 2000     910    101  1895      31           13  2950</code></pre>
<div id="data-import" class="section level3">
<h3>Data import</h3>
<p>We directly import the data from the excel file, selecting only the
range that contains the data, and then setting the column names
accordingly.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#importing data directly from excel</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/Electricity export Switzerland.xlsx&quot;</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">range =</span> <span class="st">&quot;A6:G280&quot;</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## New names:
## • `` -&gt; `...1`
## • `` -&gt; `...2`
## • `` -&gt; `...3`
## • `` -&gt; `...4`
## • `` -&gt; `...5`
## • `` -&gt; `...6`
## • `` -&gt; `...7`</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Setting column names</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data_elec) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&#39;Date&#39;</span>,<span class="st">&#39;Germany&#39;</span>,<span class="st">&#39;France&#39;</span>,<span class="st">&#39;Italy&#39;</span>,<span class="st">&#39;Austria&#39;</span>,<span class="st">&#39;Lichtenstein&#39;</span>,<span class="st">&#39;Total&#39;</span>)</span></code></pre></div>
</div>
<div id="data-cleaning-1" class="section level3">
<h3>Data cleaning</h3>
<p>Looking at the data we see that October is written with a “k”, so we
change that in the Date column. Then we check for missing values, before
proceeding.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># replace &quot;Oktober&quot; with &quot;October&quot; in the Date column</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_elec<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(data_elec<span class="sc">$</span>Date, <span class="st">&quot;Oktober&quot;</span>, <span class="st">&quot;October&quot;</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#This uses the &quot;DataExplorer&quot; package</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_intro</span>(data_elec)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-3-1.png" width="768" /></p>
</div>
<div
id="converting-to-tsibble-so-that-we-can-use-the-fpp3-and-tsibble-package-functions"
class="section level3">
<h3>Converting to tsibble so that we can use the fpp3 and tsibble
package functions</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert to tsibble </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(Date)) <span class="sc">%&gt;%</span> <span class="co">#need to do this before converting to get proper format</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> Date)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#check that it&#39;s a tsibble now, and we can see it recognized the data is monthly because of the [1M] </span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">is_tsibble</span>(data_elec)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data_elec</span></code></pre></div>
<pre><code>## # A tsibble: 275 x 7 [1M]
##        Date Germany France Italy Austria Lichtenstein Total
##       &lt;mth&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1 2000 Jan     421    313  1760       3           24  2521
##  2 2000 Feb     412    141  1757       4           23  2337
##  3 2000 Mar     459    148  1962       4           23  2596
##  4 2000 Apr     474    114  1767       3           17  2375
##  5 2000 May     935    116  1927      42           14  3034
##  6 2000 Jun     910    101  1895      31           13  2950
##  7 2000 Jul     510    105  1950      16           14  2595
##  8 2000 Aug     612    152  1275      39           14  2092
##  9 2000 Sep     354    320  1849      18           17  2558
## 10 2000 Oct     439    291  2295      28           20  3073
## # ℹ 265 more rows</code></pre>
</div>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<div id="questions" class="section level4">
<h4>Questions</h4>
<ul>
<li>Explain why the peak electricity exports happen in the summer months
instead of the winter months.</li>
</ul>
<p><img src="main_files/figure-html/EDA-1.png" width="768" /><img src="main_files/figure-html/EDA-2.png" width="768" /><img src="main_files/figure-html/EDA-3.png" width="768" /><img src="main_files/figure-html/EDA-4.png" width="768" /><img src="main_files/figure-html/EDA-5.png" width="768" /><img src="main_files/figure-html/EDA-6.png" width="768" /></p>
<p>Some observations:</p>
<ul>
<li>Germany: Energy exports seem to be varying in variance over time,
being a lot more volatile since 2012. This suggests multiplicative
errors?</li>
<li>France: Similarly to Germany, exports become more volatile over
time. Big peak in 2011?</li>
<li>Italy: Less variability in the variance over time compared to the
precious two.</li>
<li>Austria: Big peak in 2002ish, could be an outliar. Exports
oscillating close to 0 until 2014, since then much more volatile and
higher in volume.</li>
<li>Lichtenstein: Big drop in level of exports during 2008-2009. Why did
that happen? Should probably only use more recent data for predictions,
because older data is very different.</li>
<li>Total: Data oscillating around the same level, no signs of
seasonality which indicates white noise data. This is good for making
the models.</li>
</ul>
<p>To further analyze the data, we created monthly historical graphs
(Seasonal Subseries plots)</p>
<p>Before looking at the following graphs, we would expect that more
energy is needed in the winter months compared to the winter months,
because in winter there are less hours of sunlight (people need to light
up their houses for longer) and people also need to warm up their homes
more because it’s colder outside compared to the summer months.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Seasonal Subseries Plots</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(Germany) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to Germany&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-1.png" width="768" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(France) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to France&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-2.png" width="768" /></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(Italy) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to Italy&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-3.png" width="768" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(Austria) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to Austria&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-4.png" width="768" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(Lichtenstein) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to Lichtenstein&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-5.png" width="768" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">gg_subseries</span>(Total) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Seasonal subseries plot: Swiss electricity exported to All countries&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-5-6.png" width="768" /></p>
<p>Some observations:</p>
<ul>
<li>Germany: It looks like Germany consistently receives more
electricity during the summer months (May, June, July, August). Why is
that? Is it because German electricity production is lower during the
summer months and they decide to import from Switzerland? Or that
Germany has a higher energy need in the summer?</li>
<li>France: It looks like there are two peaks in energy exported to
France during the year, one in July, and one in December.<br />
</li>
<li>Italy: Another peak for energy in July. Why are all countries
importing the most electricity in the summer months?</li>
<li>Austria: Same trend, with a single peak in the summer months, and
then relatively constant energy for the other months.</li>
<li>Lichtenstein: This country shows the opposite trend, with a very
smooth peak in the coldest winter months (Jan,Feb), and the lowest
energy exports during the summer months.<br />
</li>
<li>Total: Clearly seeing the peak in energy exports to countries in the
summer, and specifically in July. The other months are at similar level
for the total electricity exports.</li>
</ul>
<p>Conclusion on monthly subplots:</p>
<ul>
<li>We can’t think of why Lichtenstein experiences a different peak in
energy imports from Switzerland</li>
<li>It is clear that all the other countries peak in electricity imports
in the summer months, and specifically in July.</li>
</ul>
<p>This goes against our initial hypothesis about energy consumption
over the months of the year, so let’s try to explain why. - One
explanation could be that heating in the winter is powered by gas/oil
which does not require electricity directly. However, in the warm summer
months, people tend to use air-conditioning to cool their
houses/buildings down, which can only be powered directly by
electricity. This would explain why we don’t see a peak of electricity
exports in the winter months, but instead see it in the summer.</p>
</div>
</div>
<div id="autocorrelation" class="section level2">
<h2>Autocorrelation</h2>
<p>Before moving on with the models and in order to be able to use them,
we must check for autocorrelation in the time series.</p>
<div id="lets-first-look-at-a-specific-country-germany"
class="section level3">
<h3>Let’s first look at a specific country: Germany</h3>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let&#39;s look at Germany first</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the acf for 12 lagged months</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ACF</span>(Germany, <span class="at">lag_max =</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>## # A tsibble: 12 x 2 [1M]
##         lag    acf
##    &lt;cf_lag&gt;  &lt;dbl&gt;
##  1       1M  0.724
##  2       2M  0.434
##  3       3M  0.150
##  4       4M -0.103
##  5       5M -0.261
##  6       6M -0.325
##  7       7M -0.273
##  8       8M -0.120
##  9       9M  0.107
## 10      10M  0.334
## 11      11M  0.498
## 12      12M  0.610</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Graph of 12 lagged months</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_lag</span>(Germany, <span class="at">lags =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">geom=</span><span class="st">&quot;point&quot;</span>) <span class="sc">+</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Germany 12-period lag graph&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-6-1.png" width="768" /></p>
<p>From the first table produced, we can see that the autocorrelation is
highest with a lag of 1 month, and then it again goes up as we approach
the 12-month lag. This shows that our data is highly correlated on a
monthly basis (every month’s exports heavily depend on the previous
month’s exports) and we can also see a slight “seasonality” of 12
months, because every 12 months the data is highly correlated (January
of this year is very similar to January of last year)</p>
<p>From the first graph produced, we can again see the same thing, but
visualized. Here it’s a lot cleared that the autocorrelation is the
highest for the 1-month lag, and the 12-month lag. We can see this
because the points in the scatterplots approach the 45-degree line,
indicating the similarity in magnitude of two observations.</p>
<p>To visualize auto correlation differently, we can plot the acf for
each lagged period:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Still looking at Germany</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Another graphical view of Acf</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">ACF</span>(Germany) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() </span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-7-1.png" width="768" /></p>
<p>On this chart the autocorrelation coefficients are plotted by bars,
along with a 95% confidence interval. To interpret this graph, it’s
important to know that whenever a line exceeds the 95% confidence
interval, we can say that there is statistically significant
autocorrelation for a given period. Based on this, we see that:</p>
<ul>
<li>The highest autocorrelation is at a 1-month lag.</li>
<li>Every 6 months, we see that the data is strongly inversely auto
correlated. This means that every 6 months, the data is consistently
moving in opposite directions (If exports are high in July, we expect
them to be consistently lower 6 months later). This is something that we
only explored now, and was not so easy to see from the previous
graph/table.</li>
<li>Every 12 months, the data is strongly positively auto
correlated.</li>
</ul>
</div>
<div id="total-exports-autocorrelation" class="section level3">
<h3>Total exports autocorrelation</h3>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the acf for 12 lagged months</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ACF</span>(Total, <span class="at">lag_max =</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>## # A tsibble: 12 x 2 [1M]
##         lag     acf
##    &lt;cf_lag&gt;   &lt;dbl&gt;
##  1       1M  0.407 
##  2       2M  0.235 
##  3       3M  0.152 
##  4       4M  0.137 
##  5       5M  0.0956
##  6       6M  0.101 
##  7       7M  0.0580
##  8       8M  0.0174
##  9       9M -0.0530
## 10      10M -0.117 
## 11      11M -0.0891
## 12      12M  0.242</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Graph of 12 lagged months</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_lag</span>(Total, <span class="at">lags =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">geom=</span><span class="st">&quot;point&quot;</span>) <span class="sc">+</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total exports 12-period lag graph&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-8-1.png" width="768" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Another graphical view of Acf</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">ACF</span>(Total) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() </span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-8-2.png" width="768" /></p>
<p>From the graphical analysis above, we can see that when aggregating
the electricity exports to the 5 countries, we there is still a
significant autocorrelation with a lag of 1-month (each month’s exports
depend on the previous month’s exports). However, now this auto
correlation is much smaller compared to that of Germany alone (which is
a good sign for us in order to make models). Furthermore, we see a
strong auto correlation every 12 months.</p>
</div>
</div>
<div id="models" class="section level2">
<h2>Models</h2>
<div id="questions-1" class="section level3">
<h3>Questions</h3>
<ul>
<li>Naive model forecast is not showing me historical data, only the
forecast</li>
<li>Should we even bother doing a SES model (Simple exponential
smoothing)? It’s basically the same as the naive and don’t think adds
any value</li>
<li>I don’t get it: we don’t want our data to have a trend/seasonality,
but then when we select the parameters for ETS, we set them to Additive,
Multiplicative etc. In the end do we want there to be a
trend/seasonality or not?</li>
</ul>
<p>IMPORTANT - What I am basically doing, is first trying to find the
best forecasting method, and THEN I will apply it to the total + all
countries individually.</p>
</div>
<div id="todo-next" class="section level3">
<h3>Todo next:</h3>
<ul>
<li>More models (Better ETS, models introduced later in the course)</li>
<li>Decomposition (haven’t done anything on this yet)</li>
</ul>
</div>
<div id="building-models---only-looking-at-total-exports-for-now"
class="section level3">
<h3>Building models - Only looking at Total exports for now</h3>
<p>In the world of forecasting, we can’t get a perfect forecast no
matter how hard we try. Also, making a model more complicated won’t
necessarily make it more accurate. Finally, when trying to forecast it’s
important to take into consideration how much time is spent on a
forecast, versus how much valuable information we get out of it. It is
therefore important to consider simpler, more “naive” models to try and
make predictions about the future, before moving on to more complicated
ones.</p>
</div>
<div id="naive-model" class="section level3">
<h3>Naive model</h3>
<p>The naive model we are going to use is simply a forecast that is
equal to the latest observation.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating and Plotting the naive model</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>naive_fit <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">model</span>(<span class="fu">NAIVE</span>(Total))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(naive_fit) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Total, <span class="at">colour =</span> <span class="st">&quot;Data&quot;</span>)) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">colour =</span> <span class="st">&quot;Fitted&quot;</span>)) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Data =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">Fitted =</span> <span class="st">&quot;orange&quot;</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> <span class="fu">guides</span>(<span class="at">colour =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">&quot;Series&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values (`geom_line()`).</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-9-1.png" width="768" /></p>
<p>This plot is basically shows the original data, and then a copy of it
which is moved one period in the future.</p>
<p>Now let’s look at the residuals of the naive forecasting model, and
search for autocorrelation. It is important to do so, because if there
is autocorrelation in a the residuals of a forecasting model, this means
that the model is not capturing some of the important features of the
data, and might be leading to an inaccurate forecast. We will use the
Portmanteau (Ljung-box) test:</p>
<p>This test checks for the presence of autocorrelation in the
residuals, by testing the following null hypothesis: <span
class="math inline">\(H_0:\)</span> The residuals are independently and
identically distributed (IID) with a normal distribution. If the p-value
of the test is less than the chosen significance level (example <span
class="math inline">\(\alpha= 0.05\)</span>), then we reject the null
hypothesis and conclude that there is evidence of autocorrelation in the
residuals.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plotting the residuals of the naive method</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>aug <span class="ot">&lt;-</span> naive_fit <span class="sc">%&gt;%</span> <span class="fu">augment</span>()</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(aug, .resid) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Residual&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Residuals from naïve method&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values (`geom_line()`).</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-10-1.png" width="768" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Box-pierce test</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>aug <span class="sc">%&gt;%</span> <span class="fu">features</span>(.resid, box_pierce, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">dof =</span> <span class="dv">0</span>) <span class="co">#The degrees of freedom (dof) are 0 for the naive method</span></span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .model       bp_stat bp_pvalue
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 NAIVE(Total)    40.4 0.0000143</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ljung test</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>aug <span class="sc">%&gt;%</span> <span class="fu">features</span>(.resid, ljung_box, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">dof =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .model       lb_stat lb_pvalue
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 NAIVE(Total)    41.0 0.0000115</code></pre>
<p>From both the Box-pierce and Ljung tests, we can see that the p-value
is very small (very close to 0) which indicates the presence of
autocorrelation in the residuals. This means that the residuals are not
white noise, which is not good and we will have to work around it.</p>
</div>
<div id="forecast-for-the-next-6-months-using-the-naive-model"
class="section level3">
<h3>Forecast for the next 6 months using the Naive model:</h3>
<p>Now that we have built the naive model, and explained that it might
be inaccurate due to the presence of autocorrelation, let’s create a
forecast using it:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>naive_fc <span class="ot">&lt;-</span> fabletools<span class="sc">::</span><span class="fu">forecast</span>(naive_fit, <span class="at">h =</span> <span class="dv">6</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(naive_fc) <span class="sc">+</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Date&quot;</span>) <span class="sc">+</span> </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Electricity Exports&quot;</span>) <span class="sc">+</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Naive Forecast for 6 months - Total Electricity Exports&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-11-1.png" width="768" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the forecast object to a tibble to be able to use it with the kable function</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>forecast_tbl_naive <span class="ot">&lt;-</span> naive_fc <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Date, .mean)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the kable function to display the table</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(forecast_tbl_naive, <span class="at">format =</span> <span class="st">&quot;markdown&quot;</span>, </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Date&quot;</span>, <span class="st">&quot;Forecast&quot;</span>), </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">&quot;cccc&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Date</th>
<th align="center">Forecast</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2022 Dec</td>
<td align="center">2410</td>
</tr>
<tr class="even">
<td align="center">2023 Jan</td>
<td align="center">2410</td>
</tr>
<tr class="odd">
<td align="center">2023 Feb</td>
<td align="center">2410</td>
</tr>
<tr class="even">
<td align="center">2023 Mar</td>
<td align="center">2410</td>
</tr>
<tr class="odd">
<td align="center">2023 Apr</td>
<td align="center">2410</td>
</tr>
<tr class="even">
<td align="center">2023 May</td>
<td align="center">2410</td>
</tr>
</tbody>
</table>
<p>As expected, the output of the Naive forecast is a flat line. This is
because in this model, each forecast is equal to the value in the
previous period. This isn’t very useful and accurate, so we have to use
more complicated and sophisticated models for the rest of this
analysis.</p>
</div>
<div id="ets-model---exponential-smoothing" class="section level3">
<h3>ETS model - Exponential Smoothing</h3>
<p>ETS stands for Error-Trend-Seasonality, and is one of the most robust
and commonly used forecasting methods in the industry.</p>
<p>ETS is based on the idea that more recent observations should be
given more importance when creating a forecast. It’s a method that
allocates weights to each observation, and the weights are bigger, the
more recent the data is. As we go back in time, the weights become
exponentially smaller, giving less and less weight/importance on older
data.</p>
<p>In our case, the most recent data (2020-2022) were probably heavily
impacted by Covid-19 and the war between Russia and Ukraine. This means
that an ETS model, will put more weight on more recent data, hence will
give us a biased forecast based on those two big events. We have to be
careful when selecting the weights of the ETS model, so that not too
much weight is put on the most recent data.</p>
</div>
<div id="simple-exponential-smoothing" class="section level3">
<h3>Simple Exponential Smoothing</h3>
<p>This version of Exponential smoothing, assumes that the data has no
Trend and no Seasonality:</p>
</div>
<div id="exponential-smoothing-with-different-alpha-parameters"
class="section level3">
<h3>Exponential smoothing with different alpha parameters</h3>
<p>The classical exponential smoothing function, will require a variable
alpha (<span class="math inline">\(\alpha\)</span>) which determines the
weight on different observations over time. The higher the value of
alpha, the more weight is given on more recent observations. Let’s look
at the forecast of an ETS model which gives a lot of weight on recent
observations, and much less on those further back in time.</p>
<div
id="big-weight-on-more-recent-data-in-order-to-create-a-forecast-alpha-0.8"
class="section level4">
<h4>Big weight on more recent data in order to create a forecast (Alpha
= 0.8)</h4>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The following is an ANN model with an alpha of 0.8, to show that a lot of weight is put on more recent observations</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ets_fit1 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Total <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;N&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>ets_fit1 <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">12</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(data_elec, <span class="at">level =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ETS ANN forecast with alpha = 0.8&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-13-1.png" width="768" /></p>
</div>
<div
id="less-weight-on-more-recent-data-in-order-to-create-a-forecast-alpha-0.2"
class="section level4">
<h4>Less weight on more recent data in order to create a forecast (Alpha
= 0.2)</h4>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The following is an ANN model with an alpha of 0.2, to show that less weight is put on more recent observations</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ets_fit2 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Total <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;N&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>ets_fit2 <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">12</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(data_elec, <span class="at">level =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ETS ANN forecast with alpha = 0.2&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-14-1.png" width="768" /></p>
<p>From both of these ETS forecast graphs, you can see that the forecast
is flat. This is because to make these two, we assumed no Trend and no
Seasonality in the data.</p>
<p>Also, what’s important to notice is that the forecast when alpha is
large (0.8) is much closer to the last observation, but the forecast
with a smaller alpha (0.2) is further away from the last observation.
This is because the higher the value of alpha, the more weight is put to
more recent data, as explained above.</p>
<p>There is an automated way to select the optimal alpha:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ets_fitopt <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Total <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;N&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>), <span class="at">opt_crit =</span> <span class="st">&quot;mse&quot;</span>))</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(ets_fitopt)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   .model                                                          term  estimate
##   &lt;chr&gt;                                                           &lt;chr&gt;    &lt;dbl&gt;
## 1 &quot;ETS(Total ~ error(\&quot;A\&quot;) + trend(\&quot;N\&quot;) + season(\&quot;N\&quot;), opt_… alpha    0.310
## 2 &quot;ETS(Total ~ error(\&quot;A\&quot;) + trend(\&quot;N\&quot;) + season(\&quot;N\&quot;), opt_… l[0]  2538.</code></pre>
<p>The alpha that minimizes the mean squared error, is an alpha with
value 0.310. Here’s how that forecast looks:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ets_fitopt <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">12</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(data_elec) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">colour =</span> <span class="st">&quot;Fitted&quot;</span>),  <span class="at">data=</span><span class="fu">augment</span>(ets_fitopt)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Total&quot;</span>) <span class="sc">+</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ETS ANN forecast with optimal alpha = 0.31&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-16-1.png" width="768" /></p>
<p>In the graph above, you can see in black the actual data, and in red
the smoothed values of the data, based on the optimal alpha that was
calculated. On the right side of the graph, you can see the forecast for
the next 12 period, as well as a 95% and 80% confidence interval. The
confidence intervals are huge, which is not good. We can no accurately
forecast this time series using this model.</p>
<p>This forecast is also very simple, so we will have to make things a
bit more complicated. Let’s now try playing with the parameters for
Error, Trend and Seasonality, because until now we have assumed that the
errors Additive, and that there is not trend and no seasonality in the
data.</p>
</div>
</div>
</div>
<div id="italy" class="section level2">
<h2>Italy</h2>
<div id="s-naive-model" class="section level3">
<h3>S-Naive Model</h3>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecting Italy only since 2018 to better display the forecast. 2018 will both show the trend BEFORE covid + improve display </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>Italy_since_2018 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">select</span>(Date,Italy) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2018-01-01&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: There was 1 warning in `filter()`.
## ℹ In argument: `Date &gt;= as.Date(&quot;2018-01-01&quot;)`.
## Caused by warning:
## ! Incompatible methods (&quot;&gt;=.vctrs_vctr&quot;, &quot;&gt;=.Date&quot;) for &quot;&gt;=&quot;</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling SNaive automatically</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>snaive_italy <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Italy) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">snaive =</span> <span class="fu">SNAIVE</span>(Italy, <span class="at">h =</span> <span class="dv">13</span>))</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for models</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(snaive_italy)</span></code></pre></div>
<pre><code>## Series: Italy 
## Model: SNAIVE 
## 
## sigma^2: 255289.9906</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the model</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>forecast_snaive_italy <span class="ot">&lt;-</span> snaive_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>snaive_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Italy_since_2018) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Seasonal Naive Forecast for Italy&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-18-1.png" width="768" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>forecast_table_italy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SNaive&quot;</span>),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_snaive_italy))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>forecast_table_italy <span class="ot">&lt;-</span> forecast_table_italy <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_italy)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Italy_snaive&quot;</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>forecast_table_italy</span></code></pre></div>
<pre><code>##    Italy_snaive
## 1          1133
## 2          1419
## 3          1868
## 4          1747
## 5          1544
## 6          1872
## 7          1678
## 8          2155
## 9          1456
## 10         1732
## 11         1712
## 12         2041
## 13         1133</code></pre>
</div>
<div id="ets-model" class="section level3">
<h3>ETS Model</h3>
<div id="what-is-it" class="section level4">
<h4>What is it</h4>
<p>The most basic variant of exponential smoothing is called Simple
Exponential Smoothing (SES). The method is appropriate when the time
series does not show any trend nor seasonality. It will provide a flat
forecast, similar to the average and naïve methods presented
earlier.</p>
<p>It does not make sense to use SES here, as from the decomposition we
clearly showed that the data is strongly seasonal and has a trend.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ets automatically</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ets_italy <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Italy) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Italy))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ets with trend because I know there is one! </span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>ets_italy_AAA <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Italy) <span class="sc">%&gt;%</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Italy <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;A&quot;</span>)))</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ets_italy)</span></code></pre></div>
<pre><code>## Series: Italy 
## Model: ETS(A,N,A) 
##   Smoothing parameters:
##     alpha = 0.7953408 
##     gamma = 0.0001000378 
## 
##   Initial states:
##      l[0]    s[0]    s[-1]    s[-2]     s[-3]     s[-4]   s[-5]     s[-6]
##  1996.562 10.2922 39.81835 205.8546 -126.9781 -421.2692 239.248 -147.0289
##      s[-7]     s[-8]    s[-9]   s[-10]   s[-11]
##  -154.2625 -117.9927 235.1321 146.8301 90.35606
## 
##   sigma^2:  93815.22
## 
##      AIC     AICc      BIC 
## 4708.741 4710.594 4762.992</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ets_italy_AAA)</span></code></pre></div>
<pre><code>## Series: Italy 
## Model: ETS(A,A,A) 
##   Smoothing parameters:
##     alpha = 0.7949165 
##     beta  = 0.0001001298 
##     gamma = 0.000100061 
## 
##   Initial states:
##      l[0]     b[0]     s[0]    s[-1]    s[-2]     s[-3]     s[-4]   s[-5]
##  1871.758 1.220072 1.634122 37.89373 212.3766 -122.3512 -421.8263 232.432
##      s[-6]     s[-7]     s[-8]    s[-9]   s[-10]   s[-11]
##  -152.3947 -170.4911 -117.4926 232.3587 161.9511 105.9097
## 
##   sigma^2:  94317.46
## 
##      AIC     AICc      BIC 
## 4712.094 4714.475 4773.579</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>forecast_ets_italy_ANA <span class="ot">&lt;-</span> ets_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>forecast_ets_italy_AAA <span class="ot">&lt;-</span> ets_italy_AAA <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>ets_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Italy_since_2018)<span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ETS ANA Forecast for Italy&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-19-1.png" width="768" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>ets_italy_AAA <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Italy_since_2018)<span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ETS AAA Forecast for Italy&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-19-2.png" width="768" /></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>forecast_table_italy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ETS (ANA)&quot;</span>),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_ets_italy_ANA))</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>forecast_table_italy <span class="ot">&lt;-</span> forecast_table_italy <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_italy)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Italy_ets_AAA&quot;</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="co">#components(ets_italy) %&gt;% autoplot()</span></span></code></pre></div>
<p>Performing ETS automatically (ANA) vs doing one manually (AAA), we
notice that obviously the automatic one has a smaller AIC,AICc and BIC
(because using the ETS function without arguments picks the best model
with the lowest error directly). Furthermore, plotting the forecast for
a manual AAA ETS model, we see that the two are almost completely
identical. This is why w e decided to stick with the one selected
automatically, being the ANA model.</p>
</div>
</div>
<div id="arima" class="section level3">
<h3>ARIMA</h3>
<p>ARIMA and ETS are different, but they also share quite a lot of
aspects. While ETS is focusing on trend and seasonal components, ARIMA
focuses strongly on the autocorrelation structure of time series.</p>
<p>Here’s the automatic ARIMA model, which will obvsiously do some
differencing, leading to a SARIMA model, since our data is seasonal.</p>
<p>SARIMA models incorporate both non-seasonal and seasonal components,
including autoregressive (AR), differencing (I), and moving average (MA)
terms for both the non-seasonal and seasonal components of the data.
Since our data is highly seasonal, we expect S-ARIMA to do a better job
than ARIMA.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ARIMA automatically</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>arima_italy <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Italy) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ARIMA</span>(Italy, <span class="at">stepwise =</span> <span class="cn">FALSE</span>)) <span class="co">#By default, stepwise is set to TRUE, which means the function performs a stepwise search to identify the best model by iteratively considering different model orders and selecting the model with the lowest AIC value.</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co">#However, this approach also has some potential drawbacks. The stepwise algorithm might not search through all possible models, and therefore might not find the best-fitting model. Additionally, using stepwise selection might lead to overfitting, especially if the algorithm is used iteratively to search for the &quot;best&quot; model among many different time series.</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(arima_italy) <span class="co">#ARIMA(0,1,3)(2,0,0)</span></span></code></pre></div>
<pre><code>## Series: Italy 
## Model: ARIMA(0,1,3)(2,0,0)[12] 
## 
## Coefficients:
##           ma1      ma2      ma3    sar1    sar2
##       -0.4089  -0.2934  -0.2786  0.2973  0.3197
## s.e.   0.0584   0.0745   0.0553  0.0573  0.0582
## 
## sigma^2 estimated as 98336:  log likelihood=-1964.61
## AIC=3941.22   AICc=3941.54   BIC=3962.9</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>forecast_arima_italy <span class="ot">&lt;-</span> arima_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>arima_italy <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Italy_since_2018)<span class="sc">+</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;SARIMA Forecast for Italy&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-20-1.png" width="768" /></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>forecast_table_italy_arima <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SARIMA&quot;</span>),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_arima_italy))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>forecast_table_italy_arima <span class="ot">&lt;-</span> forecast_table_italy_arima <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_italy_arima)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Italy_Arima&quot;</span></span></code></pre></div>
<p>Normally, when creating the model, the option approximation = FALSE
should be used to get the exact likelihood function, however after
running 2 versions with and without approximation we found that they
both resulted in the same arima model. This is why we kept the default
option of approximation = TRUE, as it’s much faster.</p>
<p>The model selected by the function is ARIMA(0,1,3)(2,0,0)[12], which
means it has a non-seasonal differencing of order 1 (d = 1), a moving
average (MA) component of order 3 (q = 3), and a seasonal AR component
of order 2 (P = 2), a seasonal differencing of order 0 (D = 0), and no
seasonal MA component (Q = 0).</p>
<p>The coefficients of the model are shown in the table. The values in
the first row indicate the parameter estimates for the MA terms (ma1,
ma2, ma3), and those in the second row show the parameter estimates for
the seasonal AR terms (sar1, sar2). The standard errors of the parameter
estimates are shown in the second row of numbers (se.ma1, se.ma2,
se.ma3, se.sar1, se.sar2).</p>
<p>The estimated variance of the error term (sigma^2) is 98336, and the
log-likelihood is -1964.61.</p>
<p>The presence or absence of AR components in an ARIMA model depends on
the autocorrelation structure of the time series being modeled. If there
is no evidence of autocorrelation in the series, an AR component is not
needed in the model. In this case, the data may be well-modeled by a
simpler model such as an MA (moving average) model or a seasonal model
like the SARIMA.</p>
<p>In terms of the ARIMA model we have, it’s not a surprise to see that
a differencing of order 1 has been selected. This is because our initial
data has both a trend and seasonal component as we have seen in our
decomposition. By taking the 1st-order difference of the data, the trend
and seasonal components are eliminated making the series stationary, and
allowing the ARIMA model to function.</p>
<p>Let’s verify this by looking at the differenced time-series:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting the differenced time series should show stationarity:</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>italy <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">select</span>(Italy) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">italy_diff =</span> <span class="fu">difference</span>(Italy))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>italy <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(italy_diff) <span class="sc">+</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;1st-order Differenced Exports to Italy&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values (`geom_line()`).</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-21-1.png" width="768" />
From the graph above, it is obvious that taking the 1st-order
difference, we get rid of the trend and seasonality in the data. This
creates a stationary times series which can be used in the ARIMA
model.</p>
<p>Let’s also look at the ACF plots to confirm it in a different
way:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>italyACF <span class="ot">&lt;-</span> italy <span class="sc">%&gt;%</span> <span class="fu">ACF</span>(Italy) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ACF Italy&quot;</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>italydiffACF <span class="ot">&lt;-</span> italy <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">italy_diff =</span> <span class="fu">difference</span>(Italy)) <span class="sc">%&gt;%</span> <span class="fu">ACF</span>(italy_diff) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ACF Italy Differenced&quot;</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>italyACF <span class="sc">+</span> italydiffACF</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-22-1.png" width="768" /></p>
<p>Actually from these two graphs, we see that taking the first
difference removes autocorrelation in the first 3-4 lagged periods, but
actually seems to increase the autocorrelation of data on a 12-month
lagged period.</p>
<p>Below, you can see the double differenced Italy data.</p>
<p>I DONT THINK I WANT TO KEEP THIS GRAPH:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Double differencing </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>italy <span class="sc">%&gt;%</span> <span class="fu">gg_tsdisplay</span>(<span class="fu">difference</span>(Italy, <span class="dv">12</span>) <span class="sc">%&gt;%</span> <span class="fu">difference</span>(),</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">plot_type =</span> <span class="st">&#39;partial&#39;</span>, <span class="at">lag =</span> <span class="dv">36</span>) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Double differenced&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 13 rows containing missing values (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 13 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-23-1.png" width="768" /></p>
<p>Finally, let’s take a look at the residuals of the SARIMA model:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>arima_italy <span class="sc">%&gt;%</span> <span class="fu">gg_tsresiduals</span>(<span class="at">lag_max =</span> <span class="dv">36</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;SARIMA Italy residuals analysis&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-24-1.png" width="768" /></p>
<p>From the graph above, we can actually see a lot of things. -
Heteroskedasticity: At the top, we can see the residuals over time. It
seems like there is no significant heteroskedasticity, as the variance
of the residuals is more or less constant over time. There seems to be a
bit less variance in the early years (2000-2005), but after that the
variance seems to be quite constant. This is an indication that our
model is doing a good job. - Distribution: The distribution of the
residuals (bottom-right graph) seems to be similar to a bell-curve, and
very symmetric, which is also a sign that our model has done a good job.
- ACF: There is no significant autocorrelation in the early periods,
which is again good. - Trend in the residuals: there is no trend in the
residuals, which is also a good sign.</p>
</div>
</div>
<div id="austria" class="section level2">
<h2>Austria</h2>
<p>Visualizing Austria again -&gt; looks like we shouldn’t use the whole
data for this forecast, as there is a significant change at around
2016-2018</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Austria) <span class="sc">+</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Exports from Switzerland to Austria&quot;</span>) <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-25-1.png" width="768" /></p>
<ul>
<li>Should probably do piecewise for austria since there’s a big change
in February 2018</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Investigating Austria closely since 2018, because it seems like something changed -&gt; perhaps should use Piecewise!!!</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>Austria_since_2015 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">select</span>(Date,Austria) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2015-01-01&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: There was 1 warning in `filter()`.
## ℹ In argument: `Date &gt;= as.Date(&quot;2015-01-01&quot;)`.
## Caused by warning:
## ! Incompatible methods (&quot;&gt;=.vctrs_vctr&quot;, &quot;&gt;=.Date&quot;) for &quot;&gt;=&quot;</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>Austria_since_2018 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">select</span>(Date,Austria) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2018-02-01&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: There was 1 warning in `filter()`.
## ℹ In argument: `Date &gt;= as.Date(&quot;2018-02-01&quot;)`.
## Caused by warning:
## ! Incompatible methods (&quot;&gt;=.vctrs_vctr&quot;, &quot;&gt;=.Date&quot;) for &quot;&gt;=&quot;</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Austria_since_2015)</span></code></pre></div>
<pre><code>## Plot variable not specified, automatically selected `.vars = Austria`</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-26-1.png" width="768" /></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Austria_since_2018)</span></code></pre></div>
<pre><code>## Plot variable not specified, automatically selected `.vars = Austria`</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-26-2.png" width="768" /></p>
<div id="s-naive-model-1" class="section level3">
<h3>S-Naive Model</h3>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling SNaive automatically</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>snaive_austria <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Austria) <span class="sc">%&gt;%</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">snaive =</span> <span class="fu">SNAIVE</span>(Austria, <span class="at">h =</span> <span class="dv">13</span>))</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for models</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(snaive_austria)</span></code></pre></div>
<pre><code>## Series: Austria 
## Model: SNAIVE 
## 
## sigma^2: 3351.8021</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the model</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>forecast_snaive_austria <span class="ot">&lt;-</span> snaive_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>snaive_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Austria_since_2015) <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Seasonal Naive Forecast for Austria&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-27-1.png" width="768" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>forecast_table_austria <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SNaive&quot;</span>),</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_snaive_austria))</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>forecast_table_austria <span class="ot">&lt;-</span> forecast_table_austria <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_austria)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Austria_snaive&quot;</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>forecast_table_italy</span></code></pre></div>
<pre><code>##    Italy_ets_AAA
## 1       1925.151
## 2       2005.224
## 3       2061.670
## 4       2149.965
## 5       1796.875
## 6       1760.584
## 7       1767.861
## 8       2154.101
## 9       1493.590
## 10      1787.870
## 11      2120.687
## 12      1954.703
## 13      1925.151</code></pre>
</div>
<div id="ets-model-1" class="section level3">
<h3>ETS Model</h3>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ets automatically</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>ets_austria <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Austria) <span class="sc">%&gt;%</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Austria))</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ets_austria)</span></code></pre></div>
<pre><code>## Series: Austria 
## Model: ETS(A,N,A) 
##   Smoothing parameters:
##     alpha = 0.4520354 
##     gamma = 0.0001012021 
## 
##   Initial states:
##      l[0]      s[0]     s[-1]   s[-2]     s[-3]    s[-4]    s[-5]    s[-6]
##  39.36547 -8.035093 -9.602281 -5.9864 -5.054589 30.35975 30.78646 8.201453
##     s[-7]     s[-8]     s[-9]    s[-10]    s[-11]
##  5.259591 -5.416526 -14.84667 -14.71561 -10.95008
## 
##   sigma^2:  1494.001
## 
##      AIC     AICc      BIC 
## 3570.277 3572.130 3624.528</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>forecast_ets_austria <span class="ot">&lt;-</span> ets_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>ets_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Austria_since_2015)<span class="sc">+</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ETS ANA Forecast for Austria&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-28-1.png" width="768" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>forecast_table_austria <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ETS (ANA)&quot;</span>),</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_ets_austria))</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>forecast_table_austria <span class="ot">&lt;-</span> forecast_table_austria <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_austria)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Austria_ets_ANA&quot;</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a><span class="co">#components(ets_austria) %&gt;% autoplot()</span></span></code></pre></div>
</div>
<div id="s-arima" class="section level3">
<h3>S-ARIMA</h3>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ARIMA automatically</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>arima_austria <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Austria) <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ARIMA</span>(Austria, <span class="at">stepwise =</span> <span class="cn">FALSE</span>)) <span class="co">#By default, stepwise is set to TRUE, which means the function performs a stepwise search to identify the best model by iteratively considering different model orders and selecting the model with the lowest AIC value.</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="co">#However, this approach also has some potential drawbacks. The stepwise algorithm might not search through all possible models, and therefore might not find the best-fitting model. Additionally, using stepwise selection might lead to overfitting, especially if the algorithm is used iteratively to search for the &quot;best&quot; model among many different time series.</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(arima_austria) <span class="co">#ARIMA(0,1,3)(2,0,0)</span></span></code></pre></div>
<pre><code>## Series: Austria 
## Model: ARIMA(0,1,2)(2,0,0)[12] 
## 
## Coefficients:
##           ma1      ma2    sar1    sar2
##       -0.4024  -0.4025  0.0552  0.0695
## s.e.   0.0562   0.0589  0.0620  0.0738
## 
## sigma^2 estimated as 1418:  log likelihood=-1381.52
## AIC=2773.04   AICc=2773.27   BIC=2791.11</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>forecast_arima_austria <span class="ot">&lt;-</span> arima_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>arima_austria <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Austria_since_2015)<span class="sc">+</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;SARIMA Forecast for Austria&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-29-1.png" width="768" /></p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>forecast_table_austria_arima <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SARIMA&quot;</span>),</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_arima_austria))</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>forecast_table_austria_arima <span class="ot">&lt;-</span> forecast_table_austria_arima <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_austria_arima)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Austria_Arima&quot;</span></span></code></pre></div>
</div>
</div>
<div id="france" class="section level2">
<h2>France</h2>
<ul>
<li>Looks like piecewise should be used again around 2010 and 2016
because there’s a bit downward trend since 2016 Visualizing France</li>
</ul>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(France) <span class="sc">+</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Exports from Switzerland to France&quot;</span>) <span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-30-1.png" width="768" /></p>
<p>Looks like piecewise should be used again around 2010</p>
<p>#Investigating Total closely since 2015</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>France_since_2015 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> <span class="fu">select</span>(Date,France) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2015-01-01&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: There was 1 warning in `filter()`.
## ℹ In argument: `Date &gt;= as.Date(&quot;2015-01-01&quot;)`.
## Caused by warning:
## ! Incompatible methods (&quot;&gt;=.vctrs_vctr&quot;, &quot;&gt;=.Date&quot;) for &quot;&gt;=&quot;</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(France_since_2015)</span></code></pre></div>
<pre><code>## Plot variable not specified, automatically selected `.vars = France`</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-31-1.png" width="768" /></p>
<div id="s-naive-model-2" class="section level3">
<h3>S-Naive Model</h3>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling SNaive automatically</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>snaive_france <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(France) <span class="sc">%&gt;%</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">snaive =</span> <span class="fu">SNAIVE</span>(France, <span class="at">h =</span> <span class="dv">13</span>))</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for models</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(snaive_france)</span></code></pre></div>
<pre><code>## Series: France 
## Model: SNAIVE 
## 
## sigma^2: 45743.9703</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the model</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>forecast_snaive_france <span class="ot">&lt;-</span> snaive_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>snaive_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(France_since_2015) <span class="sc">+</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Seasonal Naive Forecast for France&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-32-1.png" width="768" /></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>forecast_table_france <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SNaive&quot;</span>),</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_snaive_france))</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>forecast_table_france <span class="ot">&lt;-</span> forecast_table_france <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_france)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;France_snaive&quot;</span></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>forecast_table_france</span></code></pre></div>
<pre><code>##    France_snaive
## 1            486
## 2            546
## 3            283
## 4            539
## 5            323
## 6            224
## 7            278
## 8            603
## 9            644
## 10           505
## 11           236
## 12           118
## 13           486</code></pre>
</div>
<div id="ets-model-2" class="section level3">
<h3>ETS Model</h3>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ets automatically</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>ets_france <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(France) <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(France))</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ets_france)</span></code></pre></div>
<pre><code>## Series: France 
## Model: ETS(M,N,M) 
##   Smoothing parameters:
##     alpha = 0.129114 
##     gamma = 0.0001000038 
## 
##   Initial states:
##      l[0]     s[0]    s[-1]     s[-2]    s[-3]    s[-4]    s[-5]     s[-6]
##  170.8923 1.272475 1.045164 0.9882214 1.095887 1.156946 1.276707 0.9465757
##      s[-7]     s[-8]     s[-9]   s[-10]   s[-11]
##  0.6091215 0.6546517 0.7549087 1.001468 1.197873
## 
##   sigma^2:  0.2421
## 
##      AIC     AICc      BIC 
## 4244.319 4246.172 4298.570</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>forecast_ets_france<span class="ot">&lt;-</span> ets_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>ets_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(France_since_2015)<span class="sc">+</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ETS MNM Forecast for France&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-33-1.png" width="768" /></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>forecast_table_france_ets <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ETS (MNM)&quot;</span>),</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_ets_france))</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>forecast_table_france_ets <span class="ot">&lt;-</span> forecast_table_france_ets <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_france_ets)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;France_ets_MNM&quot;</span></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a>forecast_table_france_ets</span></code></pre></div>
<pre><code>##    France_ets_MNM
## 1        452.6419
## 2        426.1098
## 3        356.1703
## 4        268.4822
## 5        232.8623
## 6        216.6737
## 7        336.6541
## 8        454.1439
## 9        411.5258
## 10       389.8002
## 11       351.4656
## 12       371.7370
## 13       452.6433</code></pre>
<div class="sourceCode" id="cb101"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#components(ets_france) %&gt;% autoplot()</span></span></code></pre></div>
<p>Looks like it expects a jump upwards on the following month. Might be
a bit wrong, let’s compare with other models.</p>
</div>
<div id="arima-1" class="section level3">
<h3>ARIMA</h3>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling ARIMA automatically</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>arima_france <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(France) <span class="sc">%&gt;%</span></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">arima =</span> <span class="fu">ARIMA</span>(France))</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the Accuracy scores for models</span></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(arima_france)</span></code></pre></div>
<pre><code>## Series: France 
## Model: ARIMA(2,1,1)(0,0,2)[12] 
## 
## Coefficients:
##          ar1      ar2      ma1    sma1    sma2
##       0.4536  -0.0300  -0.9657  0.0771  0.1882
## s.e.  0.0637   0.0639   0.0207  0.0611  0.0596
## 
## sigma^2 estimated as 22357:  log likelihood=-1759.57
## AIC=3531.14   AICc=3531.46   BIC=3552.82</code></pre>
<div class="sourceCode" id="cb104"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the models</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>forecast_arima_france <span class="ot">&lt;-</span> arima_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>arima_france <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(France_since_2015) <span class="sc">+</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ARIMA Forecast for France&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-34-1.png" width="768" /></p>
<div class="sourceCode" id="cb105"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>forecast_table_france_a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ARIMA&quot;</span>),</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_arima_france))</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>forecast_table_france_a <span class="ot">&lt;-</span> forecast_table_france_a <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_france_a)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;France_arima&quot;</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>forecast_table_france_a</span></code></pre></div>
<pre><code>##    France_arima
## 1      263.9312
## 2      383.6005
## 3      320.5275
## 4      351.3831
## 5      353.5785
## 6      350.5107
## 7      345.8482
## 8      358.7890
## 9      345.7798
## 10     329.4261
## 11     294.9338
## 12     342.4077
## 13     376.1259</code></pre>
</div>
<div id="s-arima-1" class="section level3">
<h3>S-ARIMA</h3>
<div class="sourceCode" id="cb107"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create time series object for France up to end of 2022</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>ts_france <span class="ot">&lt;-</span> <span class="fu">ts</span>(data_elec<span class="sc">$</span>France[<span class="dv">1</span><span class="sc">:</span><span class="dv">96</span>], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2015</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create SARIMA model for France</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>sarima_france <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">arima</span>(ts_france, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>))</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for the model</span></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain residuals</span></span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> sarima_france<span class="sc">$</span>residuals</span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a>me <span class="ot">&lt;-</span> <span class="fu">mean</span>(residuals)</span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(residuals<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(residuals))</span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>mape <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(residuals<span class="sc">/</span>ts_france))</span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>accuracy_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ME =</span> me, <span class="at">RMSE =</span> rmse, <span class="at">MAE =</span> mae, <span class="at">MAPE =</span> mape)</span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(accuracy_table) <span class="ot">&lt;-</span> <span class="st">&quot;SARIMA&quot;</span></span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a>accuracy_table</span></code></pre></div>
<pre><code>##              ME    RMSE      MAE      MAPE
## SARIMA 5.126141 96.5175 73.56869 0.5202009</code></pre>
<div class="sourceCode" id="cb109"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the model</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>forecast_sarima_france <span class="ot">&lt;-</span> <span class="fu">predict</span>(sarima_france, <span class="at">n.ahead =</span> <span class="dv">13</span>, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast with confidence intervals</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(ts_france), <span class="at">y =</span> ts_france), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(forecast_sarima_france<span class="sc">$</span>pred), <span class="at">y =</span> forecast_sarima_france<span class="sc">$</span>pred), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb109-8"><a href="#cb109-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(forecast_sarima_france<span class="sc">$</span>pred), <span class="at">ymin =</span> forecast_sarima_france<span class="sc">$</span>pred <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>forecast_sarima_france<span class="sc">$</span>se,</span>
<span id="cb109-9"><a href="#cb109-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> forecast_sarima_france<span class="sc">$</span>pred <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>forecast_sarima_france<span class="sc">$</span>se), <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb109-10"><a href="#cb109-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;SARIMA Forecast for France&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;France Electricity Consumption&quot;</span>) <span class="sc">+</span></span>
<span id="cb109-11"><a href="#cb109-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2015</span>, <span class="dv">2023</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb109-12"><a href="#cb109-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb109-13"><a href="#cb109-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb109-14"><a href="#cb109-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb109-15"><a href="#cb109-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb109-16"><a href="#cb109-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb109-17"><a href="#cb109-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb109-18"><a href="#cb109-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="fl">2022.5</span>, <span class="at">y =</span> <span class="dv">535</span>, <span class="at">label =</span> <span class="st">&quot;Historical data&quot;</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb109-19"><a href="#cb109-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">2024</span>, <span class="at">y =</span> forecast_sarima_france<span class="sc">$</span>pred[<span class="dv">1</span>], <span class="at">label =</span> <span class="st">&quot;Forecast&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb109-20"><a href="#cb109-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">2024</span>, <span class="at">y =</span> forecast_sarima_france<span class="sc">$</span>pred[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">30</span>, <span class="at">label =</span> <span class="st">&quot;95% Confidence Interval&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type &lt;ts&gt;. Defaulting
## to continuous.</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-35-1.png" width="768" /></p>
<div class="sourceCode" id="cb111"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>forecast_table_france_sa <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SARIMA&quot;</span>),</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_sarima_france<span class="sc">$</span>pred))</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_france_sa)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">&quot;France_sarima&quot;</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>forecast_table_france_sa</span></code></pre></div>
<pre><code>##     Model France_sarima
## 1  SARIMA      343.6112
## 2  SARIMA      255.2717
## 3  SARIMA      234.1761
## 4  SARIMA      223.9809
## 5  SARIMA      195.1477
## 6  SARIMA      201.7458
## 7  SARIMA      291.4946
## 8  SARIMA      254.6925
## 9  SARIMA      275.4673
## 10 SARIMA      230.4771
## 11 SARIMA      283.3748
## 12 SARIMA      301.5606
## 13 SARIMA      260.4403</code></pre>
</div>
</div>
<div id="germany" class="section level2">
<h2>Germany</h2>
<p>Visualizing Germany again -&gt; looks like volatility really
increased during covid, and now going back down. Need to be careful with
forecast putting weight on much recent data because it seems heavily
influenced by covid…</p>
<div class="sourceCode" id="cb113"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>data_elec <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Germany) <span class="sc">+</span> </span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Exports from Switzerland to Germany&quot;</span>) <span class="sc">+</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;GWt&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-36-1.png" width="768" /></p>
<div class="sourceCode" id="cb114"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Investigating Germany closely since 2015</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>Germany_since_2015 <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Date,Germany) <span class="sc">%&gt;%</span> </span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2015-01-01&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: There was 1 warning in `filter()`.
## ℹ In argument: `Date &gt;= as.Date(&quot;2015-01-01&quot;)`.
## Caused by warning:
## ! Incompatible methods (&quot;&gt;=.vctrs_vctr&quot;, &quot;&gt;=.Date&quot;) for &quot;&gt;=&quot;</code></pre>
<div class="sourceCode" id="cb116"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Germany_since_2015)</span></code></pre></div>
<pre><code>## Plot variable not specified, automatically selected `.vars = Germany`</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-37-1.png" width="768" /></p>
<div id="s-naive-model-3" class="section level3">
<h3>S-Naive Model</h3>
<div class="sourceCode" id="cb118"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling snaive automatically</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>snaive_germany <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span> </span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Germany) <span class="sc">%&gt;%</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">snaive =</span> <span class="fu">SNAIVE</span>(Germany))</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for models</span></span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(snaive_germany)</span></code></pre></div>
<pre><code>## Series: Germany 
## Model: SNAIVE 
## 
## sigma^2: 51723.0156</code></pre>
<div class="sourceCode" id="cb120"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the models</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>forecast_snaive_germany <span class="ot">&lt;-</span> snaive_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>snaive_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Germany_since_2015) <span class="sc">+</span></span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Seasonal Naive Forecast for Germany&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-38-1.png" width="768" /></p>
<div class="sourceCode" id="cb121"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>forecast_table_germany <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;Seasonal Naive&quot;</span>),</span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_snaive_germany))</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a>forecast_table_germany <span class="ot">&lt;-</span> forecast_table_germany <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-7"><a href="#cb121-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_germany)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Germany_snaive&quot;</span></span>
<span id="cb121-8"><a href="#cb121-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-9"><a href="#cb121-9" aria-hidden="true" tabindex="-1"></a>forecast_table_germany</span></code></pre></div>
<pre><code>##    Germany_snaive
## 1             214
## 2             215
## 3              95
## 4             192
## 5             319
## 6             421
## 7             275
## 8             296
## 9             430
## 10            227
## 11            362
## 12            151
## 13            214</code></pre>
</div>
<div id="ets-model-3" class="section level3">
<h3>ETS Model</h3>
<div class="sourceCode" id="cb123"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelling ets automatically</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>ets_germany <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Germany) <span class="sc">%&gt;%</span></span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Germany))</span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the Accuracy scores for models</span></span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ets_germany)</span></code></pre></div>
<pre><code>## Series: Germany 
## Model: ETS(M,Ad,M) 
##   Smoothing parameters:
##     alpha = 0.7502312 
##     beta  = 0.0007319779 
##     gamma = 0.0003075178 
##     phi   = 0.9798778 
## 
##   Initial states:
##      l[0]      b[0]      s[0]     s[-1]     s[-2]    s[-3]    s[-4]  s[-5]
##  712.8072 -3.008468 0.5830932 0.6585168 0.8136262 1.051066 1.482483 1.5971
##    s[-6]    s[-7]    s[-8]     s[-9]    s[-10]    s[-11]
##  1.59693 1.821178 1.014623 0.4950621 0.3888661 0.4974555
## 
##   sigma^2:  0.1153
## 
##      AIC     AICc      BIC 
## 4123.569 4126.241 4188.671</code></pre>
<div class="sourceCode" id="cb125"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Forecasting using the models</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>forecast_ets_germany<span class="ot">&lt;-</span> ets_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Graphing the forecast</span></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a>ets_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Germany_since_2015)<span class="sc">+</span></span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ETS MAdM Forecast for Germany&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-39-1.png" width="768" /></p>
<div class="sourceCode" id="cb126"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_ets <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ETS (MAdM)&quot;</span>),</span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_ets_germany))</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_ets <span class="ot">&lt;-</span> forecast_table_germany_ets <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb126-7"><a href="#cb126-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-8"><a href="#cb126-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_germany_ets)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Germany_ets_MAdM&quot;</span></span>
<span id="cb126-9"><a href="#cb126-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-10"><a href="#cb126-10" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_ets</span></code></pre></div>
<pre><code>##    Germany_ets_MAdM
## 1          157.1304
## 2          134.0659
## 3          104.7389
## 4          133.3176
## 5          272.8334
## 6          489.8151
## 7          429.4505
## 8          429.2634
## 9          398.2749
## 10         282.1175
## 11         218.3380
## 12         176.7443
## 13         156.4080</code></pre>
<div class="sourceCode" id="cb128"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co">#components(ets_germany) %&gt;% autoplot()</span></span></code></pre></div>
</div>
<div id="arima-2" class="section level3">
<h3>ARIMA</h3>
<div class="sourceCode" id="cb129"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelling ARIMA automatically</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>arima_germany <span class="ot">&lt;-</span> data_elec <span class="sc">%&gt;%</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Germany) <span class="sc">%&gt;%</span></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">arima =</span> <span class="fu">ARIMA</span>(Germany))</span></code></pre></div>
<pre><code>## Warning in sqrt(diag(best$var.coef)): NaNs produced</code></pre>
<div class="sourceCode" id="cb131"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the Accuracy scores for models</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(arima_germany)</span></code></pre></div>
<pre><code>## Series: Germany 
## Model: ARIMA(2,0,0)(2,1,2)[12] 
## 
## Coefficients:
##          ar1     ar2     sar1    sar2    sma1     sma2
##       0.6618  0.0297  -0.2152  0.0587  -0.655  -0.1288
## s.e.     NaN     NaN      NaN     NaN     NaN      NaN
## 
## sigma^2 estimated as 20968:  log likelihood=-1685.66
## AIC=3385.32   AICc=3385.76   BIC=3410.33</code></pre>
<div class="sourceCode" id="cb133"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the models</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>forecast_arima_germany <span class="ot">&lt;-</span> arima_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>)</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast</span></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>arima_germany <span class="sc">%&gt;%</span> <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">autoplot</span>(Germany_since_2015) <span class="sc">+</span></span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;ARIMA Forecast for Germany&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-40-1.png" width="768" /></p>
<div class="sourceCode" id="cb134"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extracting the forecasted values</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_a <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;ARIMA&quot;</span>),</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_arima_germany))</span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_a <span class="ot">&lt;-</span> forecast_table_germany_a <span class="sc">%&gt;%</span> <span class="fu">select</span>(Forecast_Values..mean)</span>
<span id="cb134-6"><a href="#cb134-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb134-7"><a href="#cb134-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_germany_a)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Germany_arima&quot;</span></span>
<span id="cb134-8"><a href="#cb134-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb134-9"><a href="#cb134-9" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_a</span></code></pre></div>
<pre><code>##    Germany_arima
## 1       147.2149
## 2       163.1294
## 3       141.2789
## 4       187.9230
## 5       427.7421
## 6       712.0248
## 7       667.7915
## 8       602.9667
## 9       674.8981
## 10      370.6873
## 11      255.5486
## 12      194.3009
## 13      179.9529</code></pre>
</div>
<div id="s-arima-2" class="section level3">
<h3>S-ARIMA</h3>
<div class="sourceCode" id="cb136"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create time series object for Germany up to end of 2022</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>ts_germany <span class="ot">&lt;-</span> <span class="fu">ts</span>(data_elec<span class="sc">$</span>Germany[<span class="dv">1</span><span class="sc">:</span><span class="dv">96</span>], <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2015</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create SARIMA model for Germany</span></span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a>sarima_germany <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">arima</span>(ts_germany, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>))</span>
<span id="cb136-6"><a href="#cb136-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-7"><a href="#cb136-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the accuracy scores for the model</span></span>
<span id="cb136-8"><a href="#cb136-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain residuals</span></span>
<span id="cb136-9"><a href="#cb136-9" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> sarima_germany<span class="sc">$</span>residuals</span>
<span id="cb136-10"><a href="#cb136-10" aria-hidden="true" tabindex="-1"></a>me <span class="ot">&lt;-</span> <span class="fu">mean</span>(residuals)</span>
<span id="cb136-11"><a href="#cb136-11" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(residuals<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb136-12"><a href="#cb136-12" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(residuals))</span>
<span id="cb136-13"><a href="#cb136-13" aria-hidden="true" tabindex="-1"></a>mape <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(residuals<span class="sc">/</span>ts_germany))</span>
<span id="cb136-14"><a href="#cb136-14" aria-hidden="true" tabindex="-1"></a>accuracy_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ME =</span> me, <span class="at">RMSE =</span> rmse, <span class="at">MAE =</span> mae, <span class="at">MAPE =</span> mape)</span>
<span id="cb136-15"><a href="#cb136-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(accuracy_table) <span class="ot">&lt;-</span> <span class="st">&quot;SARIMA&quot;</span></span>
<span id="cb136-16"><a href="#cb136-16" aria-hidden="true" tabindex="-1"></a>accuracy_table</span></code></pre></div>
<pre><code>##               ME     RMSE      MAE      MAPE
## SARIMA -1.712004 134.0722 97.06387 0.2476558</code></pre>
<div class="sourceCode" id="cb138"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forecasting using the model</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>forecast_sarima_germany <span class="ot">&lt;-</span> <span class="fu">predict</span>(sarima_germany, <span class="at">n.ahead =</span> <span class="dv">13</span>, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphing the forecast with confidence intervals</span></span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(ts_germany), <span class="at">y =</span> ts_germany), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(forecast_sarima_germany<span class="sc">$</span>pred), <span class="at">y =</span> forecast_sarima_germany<span class="sc">$</span>pred), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-8"><a href="#cb138-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">time</span>(forecast_sarima_germany<span class="sc">$</span>pred), <span class="at">ymin =</span> forecast_sarima_germany<span class="sc">$</span>pred <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>forecast_sarima_germany<span class="sc">$</span>se,</span>
<span id="cb138-9"><a href="#cb138-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> forecast_sarima_germany<span class="sc">$</span>pred <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>forecast_sarima_germany<span class="sc">$</span>se), <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-10"><a href="#cb138-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;SARIMA Forecast for Germany&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Germany Electricity Consumption&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-11"><a href="#cb138-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2015</span>, <span class="dv">2023</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb138-12"><a href="#cb138-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb138-13"><a href="#cb138-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb138-14"><a href="#cb138-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb138-15"><a href="#cb138-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb138-16"><a href="#cb138-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb138-17"><a href="#cb138-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb138-18"><a href="#cb138-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="fl">2022.5</span>, <span class="at">y =</span> <span class="dv">535</span>, <span class="at">label =</span> <span class="st">&quot;Historical data&quot;</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb138-19"><a href="#cb138-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">2024</span>, <span class="at">y =</span> forecast_sarima_germany<span class="sc">$</span>pred[<span class="dv">1</span>], <span class="at">label =</span> <span class="st">&quot;Forecast&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb138-20"><a href="#cb138-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">2024</span>, <span class="at">y =</span> forecast_sarima_germany<span class="sc">$</span>pred[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">30</span>, <span class="at">label =</span> <span class="st">&quot;95% Confidence Interval&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type &lt;ts&gt;. Defaulting
## to continuous.</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-41-1.png" width="768" /></p>
<div class="sourceCode" id="cb140"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the forecasted values</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_sa <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;SARIMA&quot;</span>),</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Forecast_Values =</span> <span class="fu">c</span>(forecast_sarima_germany<span class="sc">$</span>pred))</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(forecast_table_germany_sa)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Germany_sarima&quot;</span></span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-7"><a href="#cb140-7" aria-hidden="true" tabindex="-1"></a>forecast_table_germany_sa</span></code></pre></div>
<pre><code>##     Model Germany_sarima
## 1  SARIMA       202.2027
## 2  SARIMA       197.2375
## 3  SARIMA       228.4135
## 4  SARIMA       224.1464
## 5  SARIMA       296.2393
## 6  SARIMA       345.4126
## 7  SARIMA       405.1141
## 8  SARIMA       375.6996
## 9  SARIMA       272.5324
## 10 SARIMA       328.5783
## 11 SARIMA       270.3967
## 12 SARIMA       203.7059
## 13 SARIMA       210.1653</code></pre>
</div>
</div>
</div>

   
   
            
      

  <script>
    $(document).ready(function () {

			
 		
	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
	document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>
  
</body>
</html>
