---
title: "Forecasting Project 1"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup}
library(tidyr)
library(tidyverse)
library(dplyr)

knitr::opts_chunk$set(echo = TRUE)
wd = getwd()
print(cat("Current working directory: ", wd))
setwd(wd)
```

## Project 1: Electricity export

```{r import_data}
raw_data = read.csv("data/electricity_exports.csv", header = TRUE, fill=TRUE, encoding = "UTF-8")
raw_data = data.frame(raw_data)

```

# Data cleaning
We import data and we clean it from <i>NA</i> and from blank rows. We also name the columns.
```{r data_cleaning, echo=FALSE, include=FALSE}
colnames(raw_data) = c('date', 'germany', 'france', 'italy', 'austria', 'lichtenstein', 'total')

#Removing first rows
raw_data = raw_data[-c(1:4),] 

#Selecting columns and removing NAs
clean_data= select(raw_data, date, germany, france, italy, austria, lichtenstein, total) %>% drop_na()
#Removing empty rows
clean_data = clean_data[!clean_data$date=="",]

head(clean_data)
```

```{r EDA}

#Histogram of average exports over the whole period of time across all countries


#Histogram of exports per country per year


```
