## France

- Looks like piecewise should be used again around 2010 and 2016 because there's a bit downward trend since 2016
Visualizing France

```{r}
data_elec %>% autoplot(France) + 
  ggtitle("Exports from Switzerland to France") +
  ylab("GWt") + xlab("Month")
```

Looks like piecewise should be used again around 2010

#Investigating Total closely since 2015
```{r}
France_since_2015 <- data_elec %>% select(Date,France) %>% filter(Date >= as.Date("2015-01-01"))
autoplot(France_since_2015)
```

### S-Naive Model

```{r}
# Modelling SNaive automatically
snaive_france <- data_elec %>%
  select(France) %>%
  model(snaive = SNAIVE(France, h = 13))

# Getting the accuracy scores for models
report(snaive_france)

# Forecasting using the model
forecast_snaive_france <- snaive_france %>% forecast(h = 13)

# Graphing the forecast
snaive_france %>% forecast(h = 13) %>% autoplot(France_since_2015) +
  labs(title = "Seasonal Naive Forecast for France")

# Extracting the forecasted values
forecast_table_france <- data.frame(Model = c("SNaive"),
                                    Forecast_Values = c(forecast_snaive_france))

forecast_table_france <- forecast_table_france %>% select(Forecast_Values..mean)

colnames(forecast_table_france)[1] <- "France_snaive"

forecast_table_france


```







### ETS Model 



```{r}

#Modelling ets automatically
ets_france <- data_elec %>%
  select(France) %>%
  model(ETS(France))

#Getting the Accuracy scores for models
report(ets_france)

#Forecasting using the models
forecast_ets_france<- ets_france %>% forecast(h = 13)

#Graphing the forecast
ets_france %>% forecast(h = 13) %>% autoplot(France_since_2015)+
  labs(title = "ETS MNM Forecast for France")

#Extracting the forecasted values
forecast_table_france_ets <- data.frame(Model = c("ETS (MNM)"),
                              Forecast_Values = c(forecast_ets_france))

forecast_table_france_ets <- forecast_table_france_ets %>% select(Forecast_Values..mean)

colnames(forecast_table_france_ets)[1] <- "France_ets_MNM"

forecast_table_france_ets

#components(ets_france) %>% autoplot()
```

Looks like it expects a jump upwards on the following month. Might be a bit wrong, let's compare with other models.




### ARIMA

```{r}
# Modelling ARIMA automatically
arima_france <- data_elec %>%
  select(France) %>%
  model(arima = ARIMA(France))

# Getting the Accuracy scores for models
report(arima_france)

# Forecasting using the models
forecast_arima_france <- arima_france %>% forecast(h = 13)

# Graphing the forecast
arima_france %>% forecast(h = 13) %>% autoplot(France_since_2015) +
  labs(title = "ARIMA Forecast for France")

#Extracting the forecasted values
forecast_table_france_a <- data.frame(Model = c("ARIMA"),
                              Forecast_Values = c(forecast_arima_france))

forecast_table_france_a <- forecast_table_france_a %>% select(Forecast_Values..mean)

colnames(forecast_table_france_a)[1] <- "France_arima"

forecast_table_france_a
```

### S-ARIMA

```{r}
# Create time series object for France up to end of 2022
ts_france <- ts(data_elec$France[1:96], start = c(2015, 1), frequency = 12)

# Create SARIMA model for France
sarima_france <- stats::arima(ts_france, order = c(1,1,1), seasonal = list(order = c(1,0,0), period = 12))

# Getting the accuracy scores for the model
# Obtain residuals
residuals <- sarima_france$residuals
me <- mean(residuals)
rmse <- sqrt(mean(residuals^2))
mae <- mean(abs(residuals))
mape <- mean(abs(residuals/ts_france))
accuracy_table <- data.frame(ME = me, RMSE = rmse, MAE = mae, MAPE = mape)
rownames(accuracy_table) <- "SARIMA"
accuracy_table

# Forecasting using the model
forecast_sarima_france <- predict(sarima_france, n.ahead = 13, interval = "confidence")

# Graphing the forecast with confidence intervals
ggplot() + 
  geom_line(aes(x = time(ts_france), y = ts_france), color = "blue") +
  geom_line(aes(x = time(forecast_sarima_france$pred), y = forecast_sarima_france$pred), color = "red") +
  geom_ribbon(aes(x = time(forecast_sarima_france$pred), ymin = forecast_sarima_france$pred - 1.96*forecast_sarima_france$se,
                  ymax = forecast_sarima_france$pred + 1.96*forecast_sarima_france$se), alpha = 0.3, fill = "orange") +
  labs(title = "SARIMA Forecast for France", x = "Year", y = "France Electricity Consumption") +
  scale_x_continuous(breaks = seq(2015, 2023, by = 1)) +
  theme_bw() +
  theme(plot.title = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 12)) +
  annotate("text", x = 2022.5, y = 535, label = "Historical data", color = "blue", size = 4) +
  annotate("text", x = 2024, y = forecast_sarima_germany$pred[1], label = "Forecast", color = "red", size = 4) +
  annotate("text", x = 2024, y = forecast_sarima_germany$pred[1] + 30, label = "95% Confidence Interval", color = "orange", size = 4)


# Extracting the forecasted values
forecast_table_france_sa <- data.frame(Model = c("SARIMA"),
                                     Forecast_Values = c(forecast_sarima_france$pred))

colnames(forecast_table_france_sa)[2] <- "France_sarima"

forecast_table_france_sa


```