
## Italy 

### S-Naive Model









### ETS Model 

#### What is it

The most basic variant of exponential smoothing is called Simple Exponential Smoothing (SES). The method is appropriate when the time series does not show any trend nor seasonality. It will provide a flat forecast, similar to the average and naïve methods presented earlier.

It does not make sense to use SES here, as from the decomposition we clearly showed that the data is strongly seasonal and has a trend.

```{r}
#Selecting Italy only since 2018 to better display the forecast. 2018 will both show the trend BEFORE covid + improve display 
Italy_since_2018 <- data_elec %>% select(Date,Italy) %>% filter(Date >= as.Date("2018-01-01"))



#Modelling ets automatically
ets_italy <- data_elec %>%
  select(Italy) %>%
  model(ETS(Italy))

#Modelling ets with trend because I know there is one! 
ets_italy_AAA <- data_elec %>%
  select(Italy) %>%
  model(ETS(Italy ~ error("A") + trend("A") + season("A")))

#Getting the Accuracy scores for models
report(ets_italy)
report(ets_italy_AAA)

#Forecasting using the models
forecast_ets_italy_ANA <- ets_italy %>% forecast(h = 13)
forecast_ets_italy_AAA <- ets_italy_AAA %>% forecast(h = 13)

#Graphing the forecast
ets_italy %>% forecast(h = 13) %>% autoplot(Italy_since_2018)+
  labs(title = "ETS ANA Forecast for Italy")
ets_italy_AAA %>% forecast(h = 13) %>% autoplot(Italy_since_2018)+
  labs(title = "ETS AAA Forecast for Italy")

#Extracting the forecasted values
forecast_values_ets_italy <- forecast_ets_italy_ANA$mean
forecast_values_ets_italy_AAA <- forecast_ets_italy_AAA$mean

forecast_table_italy <- data.frame(Model = c("ETS (ANA)"),
                              Forecast_Values = c(forecast_ets_italy_ANA))

forecast_table_italy <- forecast_table_italy %>% select(Forecast_Values..mean)

colnames(forecast_table_italy)[1] <- "Italy_ets_AAA"


#components(ets_italy) %>% autoplot()
```

Performing ETS automatically (ANA) vs doing one manually (AAA), we notice that obviously the automatic one has a smaller AIC,AICc and BIC (because using the ETS function without arguments picks the best model with the lowest error directly). Furthermore, plotting the forecast for a manual AAA ETS model, we see that the two are almost completely identical. This is why w   e decided to stick with the one selected automatically, being the ANA model. 



### S-ARIMA


