## Germany

Visualizing Germany again -> looks like volatility really increased during covid, and now going back down. Need to be careful with forecast putting weight on much recent data because it seems heavily influenced by covid...


```{r}
data_elec %>% autoplot(Germany) + 
  ggtitle("Exports from Switzerland to Germany") +
  ylab("GWt") + xlab("Month")
```
```{r}
# Investigating Germany closely since 2015
Germany_since_2015 <- data_elec %>% 
  select(Date,Germany) %>% 
  filter(Date >= as.Date("2015-01-01"))

autoplot(Germany_since_2015)
```


### S-Naive Model

```{r}
# Modelling snaive automatically
snaive_germany <- data_elec %>% 
  select(Germany) %>%
  model(snaive = SNAIVE(Germany))

# Getting the accuracy scores for models
report(snaive_germany)

# Forecasting using the models
forecast_snaive_germany <- snaive_germany %>% forecast(h = 13)

# Graphing the forecast
snaive_germany %>% forecast(h = 13) %>% autoplot(Germany_since_2015) +
  labs(title = "Seasonal Naive Forecast for Germany")

# Extracting the forecasted values
forecast_table_germany <- data.frame(Model = c("Seasonal Naive"),
                                     Forecast_Values = c(forecast_snaive_germany))

forecast_table_germany <- forecast_table_germany %>% select(Forecast_Values..mean)

colnames(forecast_table_germany)[1] <- "Germany_snaive"

forecast_table_germany

```








### ETS Model 


```{r}

#Modelling ets automatically
ets_germany <- data_elec %>%
  select(Germany) %>%
  model(ETS(Germany))

#Getting the Accuracy scores for models
report(ets_germany)

#Forecasting using the models
forecast_ets_germany<- ets_germany %>% forecast(h = 13)

#Graphing the forecast
ets_germany %>% forecast(h = 13) %>% autoplot(Germany_since_2015)+
  labs(title = "ETS MAdM Forecast for Germany")

#Extracting the forecasted values

forecast_table_germany_ets <- data.frame(Model = c("ETS (MAdM)"),
                              Forecast_Values = c(forecast_ets_germany))

forecast_table_germany_ets <- forecast_table_germany_ets %>% select(Forecast_Values..mean)

colnames(forecast_table_germany_ets)[1] <- "Germany_ets_MAdM"

forecast_table_germany_ets

#components(ets_germany) %>% autoplot()
```









### ARIMA

```{r}
# Modelling ARIMA automatically
arima_germany <- data_elec %>%
  select(Germany) %>%
  model(arima = ARIMA(Germany))

# Getting the Accuracy scores for models
report(arima_germany)

# Forecasting using the models
forecast_arima_germany <- arima_germany %>% forecast(h = 13)

# Graphing the forecast
arima_germany %>% forecast(h = 13) %>% autoplot(Germany_since_2015) +
  labs(title = "ARIMA Forecast for Germany")

#Extracting the forecasted values
forecast_table_germany_a <- data.frame(Model = c("ARIMA"),
                              Forecast_Values = c(forecast_arima_germany))

forecast_table_germany_a <- forecast_table_germany_a %>% select(Forecast_Values..mean)

colnames(forecast_table_germany_a)[1] <- "Germany_arima"

forecast_table_germany_a

```


### S-ARIMA
```{r}

# Create time series object for Germany up to end of 2022
ts_germany <- ts(data_elec$Germany[1:96], start = c(2015, 1), frequency = 12)

# Create SARIMA model for Germany
sarima_germany <- stats::arima(ts_germany, order = c(1,1,1), seasonal = list(order = c(1,0,0), period = 12))

# Getting the accuracy scores for the model
# Obtain residuals
residuals <- sarima_germany$residuals
me <- mean(residuals)
rmse <- sqrt(mean(residuals^2))
mae <- mean(abs(residuals))
mape <- mean(abs(residuals/ts_germany))
accuracy_table <- data.frame(ME = me, RMSE = rmse, MAE = mae, MAPE = mape)
rownames(accuracy_table) <- "SARIMA"
accuracy_table

# Forecasting using the model
forecast_sarima_germany <- predict(sarima_germany, n.ahead = 13, interval = "confidence")

# Graphing the forecast with confidence intervals
ggplot() + 
  geom_line(aes(x = time(ts_germany), y = ts_germany), color = "blue") +
  geom_line(aes(x = time(forecast_sarima_germany$pred), y = forecast_sarima_germany$pred), color = "red") +
  geom_ribbon(aes(x = time(forecast_sarima_germany$pred), ymin = forecast_sarima_germany$pred - 1.96*forecast_sarima_germany$se,
                  ymax = forecast_sarima_germany$pred + 1.96*forecast_sarima_germany$se), alpha = 0.3, fill = "orange") +
  labs(title = "SARIMA Forecast for Germany", x = "Year", y = "Germany Electricity Consumption") +
  scale_x_continuous(breaks = seq(2015, 2023, by = 1)) +
  theme_bw() +
  theme(plot.title = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 12)) +
  annotate("text", x = 2022.5, y = 535, label = "Historical data", color = "blue", size = 4) +
  annotate("text", x = 2024, y = forecast_sarima_germany$pred[1], label = "Forecast", color = "red", size = 4) +
  annotate("text", x = 2024, y = forecast_sarima_germany$pred[1] + 30, label = "95% Confidence Interval", color = "orange", size = 4)


# Extracting the forecasted values
forecast_table_germany_sa <- data.frame(Model = c("SARIMA"),
                                     Forecast_Values = c(forecast_sarima_germany$pred))

colnames(forecast_table_germany_sa)[2] <- "Germany_sarima"

forecast_table_germany_sa

```





