
## Total 

```{r}
data_elec %>% autoplot(Total) + 
  ggtitle("Exports from Switzerland to all countries") +
  ylab("GWt") + xlab("Month")
```


#Investigating Total closely since 2015
```{r}
Total_since_2015 <- data_elec %>% select(Date,Total) %>% filter(Date >= as.Date("2015-01-01"))
autoplot(Total_since_2015)
```

### S-Naive Model

```{r}
# Modelling SNaive automatically
snaive_total <- data_elec %>%
  select(Total) %>%
  model(snaive = SNAIVE(Total, h = 13))

# Getting the accuracy scores for models
report(snaive_total)

# Forecasting using the model
forecast_snaive_total <- snaive_total %>% forecast(h = 13)

#Checking the residuals before forecasting
snaive_total %>% gg_tsresiduals(lag_max = 36) + labs(title = "ETS residuals analysis for all countries")

# Graphing the forecast
snaive_total %>% forecast(h = 13) %>% autoplot(Total_since_2015) +
  labs(title = "Seasonal Naive Forecast to all countries")

# Extracting the forecasted values
forecast_table_total <- data.frame(Model = c("SNaive"),
                                    Forecast_Values = c(forecast_snaive_total))

forecast_table_total <- forecast_table_total %>% select(Forecast_Values..mean)

colnames(forecast_table_total)[1] <- "Total_snaive"

forecast_table_total


```








### ETS Model 

```{r}

#Modelling ets automatically
ets_total <- data_elec %>%
  select(Total) %>%
  model(ETS(Total))

#Getting the Accuracy scores for models
report(ets_total)

#Forecasting using the models
forecast_ets_total<- ets_total %>% forecast(h = 13)

#Checking the residuals before forecasting
ets_total %>% gg_tsresiduals(lag_max = 36) + labs(title = "ETS residuals analysis for all countries")

#Graphing the forecast
ets_total %>% forecast(h = 13) %>% autoplot(Total_since_2015)+
  labs(title = "ETS ANA Forecast for all countries")

#Extracting the forecasted values

forecast_table_total <- data.frame(Model = c("ETS (ANA)"),
                              Forecast_Values = c(forecast_ets_total))

forecast_table_total <- forecast_table_total %>% select(Forecast_Values..mean)

colnames(forecast_table_total)[1] <- "All_countries_ets_ANA"


#components(ets_total) %>% autoplot()
```





### S-ARIMA
```{r}
# Modelling ARIMA automatically
arima_total <- data_elec %>%
  select(Total) %>%
  model(arima = ARIMA(Total))

# Getting the Accuracy scores for models
report(arima_total)

# Forecasting using the models
forecast_arima_total <- arima_total %>% forecast(h = 13)

#Checking the residuals before forecasting
arima_total %>% gg_tsresiduals(lag_max = 36) + labs(title = "SARIMA residuals analysis for all countries")


# Graphing the forecast
arima_total %>% forecast(h = 13) %>% autoplot(Total_since_2015) +
  labs(title = "ARIMA Forecast for all countries")

#Extracting the forecasted values
forecast_table_total_a <- data.frame(Model = c("ARIMA"),
                              Forecast_Values = c(forecast_arima_total))

forecast_table_total_a <- forecast_table_total_a %>% select(Forecast_Values..mean)

colnames(forecast_table_total_a)[1] <- "Total_arima"

forecast_table_total_a
```




