
# Austria

Visualizing Austria again -> looks like we shouldn't use the whole data for this forecast, as there is a significant change at around 2016-2018

```{r}
data_elec %>% autoplot(Austria) + 
  ggtitle("Exports from Switzerland to Austria") +
  ylab("GWt") + xlab("Month")
```

- Should probably do piecewise for austria since there's a big change in February 2018

```{r}
#Investigating Austria closely since 2018, because it seems like something changed -> perhaps should use Piecewise!!!
Austria_since_2015 <- data_elec %>% select(Date,Austria) %>% filter(Date >= as.Date("2015-01-01"))
Austria_since_2018 <- data_elec %>% select(Date,Austria) %>% filter(Date >= as.Date("2018-02-01"))
autoplot(Austria_since_2015)
autoplot(Austria_since_2018)
```

## S-Naive Model

```{r}
# Modelling SNaive automatically
snaive_austria <- data_elec %>%
  select(Austria) %>%
  model(snaive = SNAIVE(Austria, h = 13))

# Getting the accuracy scores for models
report(snaive_austria)

# Forecasting using the model
forecast_snaive_austria <- snaive_austria %>% forecast(h = 13)

# Graphing the forecast
snaive_austria %>% forecast(h = 13) %>% autoplot(Austria_since_2015) +
  labs(title = "Seasonal Naive Forecast for Austria")

# Extracting the forecasted values
forecast_table_austria <- data.frame(Model = c("SNaive"),
                                    Forecast_Values = c(forecast_snaive_austria))

forecast_table_austria <- forecast_table_austria %>% select(Forecast_Values..mean)

colnames(forecast_table_austria)[1] <- "Austria_snaive"

forecast_table_italy
```

## ETS Model 

```{r}

#Modelling ets automatically
ets_austria <- data_elec %>%
  select(Austria) %>%
  model(ETS(Austria))

#Getting the Accuracy scores for models
report(ets_austria)

#Forecasting using the models
forecast_ets_austria <- ets_austria %>% forecast(h = 13)

#Graphing the forecast
ets_austria %>% forecast(h = 13) %>% autoplot(Austria_since_2015)+
  labs(title = "ETS ANA Forecast for Austria")

#Extracting the forecasted values

forecast_table_austria <- data.frame(Model = c("ETS (ANA)"),
                              Forecast_Values = c(forecast_ets_austria))

forecast_table_austria <- forecast_table_austria %>% select(Forecast_Values..mean)

colnames(forecast_table_austria)[1] <- "Austria_ets_ANA"


#components(ets_austria) %>% autoplot()
```

## S-ARIMA

```{r}

#Modelling ARIMA automatically
arima_austria <- data_elec %>%
  select(Austria) %>%
  model(ARIMA(Austria, stepwise = FALSE)) #By default, stepwise is set to TRUE, which means the function performs a stepwise search to identify the best model by iteratively considering different model orders and selecting the model with the lowest AIC value.
#However, this approach also has some potential drawbacks. The stepwise algorithm might not search through all possible models, and therefore might not find the best-fitting model. Additionally, using stepwise selection might lead to overfitting, especially if the algorithm is used iteratively to search for the "best" model among many different time series.

#Getting the Accuracy scores for models
report(arima_austria) #ARIMA(0,1,3)(2,0,0)

#Forecasting using the models
forecast_arima_austria <- arima_austria %>% forecast(h = 13)

#Graphing the forecast
arima_austria %>% forecast(h = 13) %>% autoplot(Austria_since_2015)+
  labs(title = "SARIMA Forecast for Austria")

#Extracting the forecasted values
forecast_table_austria_arima <- data.frame(Model = c("SARIMA"),
                              Forecast_Values = c(forecast_arima_austria))

forecast_table_austria_arima <- forecast_table_austria_arima %>% select(Forecast_Values..mean)

colnames(forecast_table_austria_arima)[1] <- "Austria_Arima"

```


